source code: https://www.datacamp.com/community/tutorials/web-scraping-using-python

# Scraping NBA Advanced Player Stats

In [1]:
#Import dependencies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from urllib.request import urlopen
from bs4 import BeautifulSoup
import re

In [2]:
#URLs for for loop
urls = ["https://www.basketball-reference.com/leagues/NBA_2020_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_2019_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_2018_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_2017_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_2016_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_2015_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_2014_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_2013_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_2012_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_2011_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_2010_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_2009_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_2008_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_2007_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_2006_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_2005_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_2004_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_2003_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_2002_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_2001_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_2000_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_1999_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_1998_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_1997_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_1996_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_1995_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_1994_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_1993_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_1992_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_1991_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_1990_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_1989_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_1988_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_1987_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_1986_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_1985_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_1984_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_1983_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_1982_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_1981_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_1980_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_1979_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_1978_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_1977_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_1976_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_1975_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_1974_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_1973_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_1972_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_1971_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_1970_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_1969_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_1968_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_1967_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_1966_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_1965_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_1964_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_1963_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_1962_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_1961_advanced.html",
"https://www.basketball-reference.com/leagues/NBA_1960_advanced.html"]

In [3]:
#For loop to create dataframe of season stats
#testing it out with only 2 URLs

list_rows = []
season = []

#iterate over each URL
for url in urls:
    html = urlopen(url)
    soup = BeautifulSoup(html, 'lxml')
    rows = soup.find_all('tr')
    title = soup.title.get_text()[0:7]
    print(title, "finished scraping")

#iterate over each row to clean it up and add it to a list of the rows
    for row in rows:
        cells = row.find_all('td')
        str_cells = str(cells)
        clean = re.compile('<.*?>')
        clean2 = (re.sub(clean, '',str_cells))
        list_rows.append(clean2)
        season.append(title)

2019-20 finished scraping
2018-19 finished scraping
2017-18 finished scraping
2016-17 finished scraping
2015-16 finished scraping
2014-15 finished scraping
2013-14 finished scraping
2012-13 finished scraping
2011-12 finished scraping
2010-11 finished scraping
2009-10 finished scraping
2008-09 finished scraping
2007-08 finished scraping
2006-07 finished scraping
2005-06 finished scraping
2004-05 finished scraping
2003-04 finished scraping
2002-03 finished scraping
2001-02 finished scraping
2000-01 finished scraping
1999-00 finished scraping
1998-99 finished scraping
1997-98 finished scraping
1996-97 finished scraping
1995-96 finished scraping
1994-95 finished scraping
1993-94 finished scraping
1992-93 finished scraping
1991-92 finished scraping
1990-91 finished scraping
1989-90 finished scraping
1988-89 finished scraping
1987-88 finished scraping
1986-87 finished scraping
1985-86 finished scraping
1984-85 finished scraping
1983-84 finished scraping
1982-83 finished scraping
1981-82 finished scraping
1980-81 finished scraping
1979-80 finished scraping
1978-79 finished scraping
1977-78 finished scraping
1976-77 finished scraping
1975-76 finished scraping
1974-75 finished scraping
1973-74 finished scraping
1972-73 finished scraping
1971-72 finished scraping
1970-71 finished scraping
1969-70 finished scraping
1968-69 finished scraping
1967-68 finished scraping
1966-67 finished scraping
1965-66 finished scraping
1964-65 finished scraping
1963-64 finished scraping
1962-63 finished scraping
1961-62 finished scraping
1960-61 finished scraping
1959-60 finished scraping

In [4]:
df = pd.DataFrame(list_rows)

In [5]:
df['Season']=season

In [6]:
df.set_axis(['0','Season'], axis=1, inplace=False)

                                                       0   Season
0                                                     []  2019-20
1      [Steven Adams, C, 26, OKC, 58, 1564, 20.8, .60...  2019-20
2      [Bam Adebayo, PF, 22, MIA, 65, 2235, 20.6, .60...  2019-20
3      [LaMarcus Aldridge, C, 34, SAS, 53, 1754, 19.8...  2019-20
4      [Nickeil Alexander-Walker, SG, 21, NOP, 41, 50...  2019-20
...                                                  ...      ...
26244  [Jack Twyman*, SF, 25, CIN, 75, 3023, 21.1, .4...  1959-60
26245  [Charlie Tyra, C, 24, NYK, 74, 2033, 12.8, .45...  1959-60
26246  [Win Wilfong, PG, 26, CIN, 72, 1992, 11.0, .42...  1959-60
26247  [Tony Windis, PG, 27, DET, 9, 193, 7.5, .287, ...  1959-60
26248  [George Yardley*, SF, 31, SYR, 73, 2402, 18.2,...  1959-60

[26249 rows x 2 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26249 entries, 0 to 26248
Data columns (total 2 columns):
0         26249 non-null object
Season    26249 non-null object
dtypes: object(2)
memory usage: 410.3+ KB

In [8]:
i = df.columns.get_loc(0)
df2 = df[0].str.split(",", expand=True)
df2=pd.concat([df.iloc[:, :i], df2, df.iloc[:, i+1:]], axis=1)

In [9]:
df2[0] = df2[0].str.strip('[')
df2[27] = df2[27].str.strip(']')
df2 = df2.iloc[2:]
df2 = df2.reset_index(drop=True)

In [10]:
df2 = df2.set_axis(['Player', 'Pos', 'Age', 'Tm', 'G', 'MP', 'PER', 'TSpct', '3PAr', 'FTr', 'ORBpct', 'DRBpct', 'TRBpct', 'ASTpct', 'STLpct', 'BLKpct', 'TOVpct', 'USGpct', '18', 'OWS', 'DWS', 'WS', 'WS/48', '23', 'OBPM', 'DBPM', 'BPM','VORP','Season'], axis=1, inplace=False)
df2.reset_index
df2.drop(df2[df2['Player'] == ']'].index, inplace = True)
df2.reset_index(drop=True)

,Player,Pos,Age,Tm,G,MP,PER,TSpct,3PAr,FTr,...,OWS,DWS,WS,WS/48,23,OBPM,DBPM,BPM,VORP,Season
0,Bam Adebayo,PF,22,MIA,65,2235,20.6,.606,.018,.476,...,4.6,3.6,8.1,.175,,1.6,2.1,3.6,3.2,2019-20
1,LaMarcus Aldridge,C,34,SAS,53,1754,19.8,.571,.198,.241,...,3.1,1.4,4.4,.122,,1.8,-0.5,1.3,1.5,2019-20
2,Nickeil Alexander-Walker,SG,21,NOP,41,501,7.6,.441,.515,.123,...,-0.7,0.4,-0.4,-0.034,,-3.5,-1.4,-4.9,-0.4,2019-20
3,Grayson Allen,SG,24,MEM,30,498,11.4,.577,.517,.199,...,0.5,0.3,0.7,.070,,-1.0,-1.5,-2.6,-0.1,2019-20
4,Jarrett Allen,C,21,BRK,64,1647,20.3,.658,.012,.574,...,4.3,2.8,7.1,.207,,1.0,1.1,2.1,1.7,2019-20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25181,Jack Twyman*,SF,25,CIN,75,3023,21.1,.487,,.369,...,7.6,0.7,8.3,.131,,,,,,1959-60
25182,Charlie Tyra,C,24,NYK,74,2033,12.8,.456,,.199,...,1.4,0.8,2.3,.053,,,,,,1959-60
25183,Win Wilfong,PG,26,CIN,72,1992,11.0,.425,,.271,...,0.2,0.5,0.6,.015,,,,,,1959-60
25184,Tony Windis,PG,27,DET,9,193,7.5,.287,,.100,...,-0.4,0.2,-0.2,-0.057,,,,,,1959-60
25185,George Yardley*,SF,31,SYR,73,2402,18.2,.522,,.388,...,6.9,2.1,9.0,.179,,,,,,1959-60

In [11]:
df2=df2.drop(columns=['18','23'])

In [12]:
df2.to_csv('../Capstone/Data/NBA_Advanced_Data.csv', index=0)