source code: https://www.datacamp.com/community/tutorials/web-scraping-using-python

In [1]:
#Import dependencies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from urllib.request import urlopen
from bs4 import BeautifulSoup
import re

In [2]:
#URLs for for loop
urls = ["https://www.hockey-reference.com/leagues/NHL_2020_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_2019_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_2018_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_2017_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_2016_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_2015_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_2014_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_2013_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_2012_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_2011_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_2010_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_2009_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_2008_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_2007_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_2006_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_2005_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_2004_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_2003_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_2002_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_2001_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_2000_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_1999_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_1998_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_1997_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_1996_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_1995_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_1994_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_1993_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_1992_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_1991_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_1990_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_1989_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_1988_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_1987_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_1986_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_1985_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_1984_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_1983_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_1982_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_1981_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_1980_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_1979_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_1978_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_1977_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_1976_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_1975_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_1974_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_1973_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_1972_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_1971_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_1970_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_1969_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_1968_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_1967_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_1966_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_1965_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_1964_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_1963_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_1962_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_1961_skaters.html",
"https://www.hockey-reference.com/leagues/NHL_1960_skaters.html"]

In [3]:
#For loop to create dataframe of season stats
#testing it out with only 2 URLs

list_rows = []
season = []

#iterate over each URL
for url in urls:
    html = urlopen(url)
    soup = BeautifulSoup(html, 'lxml')
    rows = soup.find_all('tr')
    title = soup.title.get_text()[0:7]
    print(title, "finished scraping")

#iterate over each row to clean it up and add it to a list of the rows
    for row in rows:
        cells = row.find_all('td')
        str_cells = str(cells)
        clean = re.compile('<.*?>')
        clean2 = (re.sub(clean, '',str_cells))
        list_rows.append(clean2)
        season.append(title)

2019-20 finished scraping
2018-19 finished scraping
2017-18 finished scraping
2016-17 finished scraping
2015-16 finished scraping
2014-15 finished scraping
2013-14 finished scraping
2012-13 finished scraping
2011-12 finished scraping
2010-11 finished scraping
2009-10 finished scraping
2008-09 finished scraping
2007-08 finished scraping
2006-07 finished scraping
2005-06 finished scraping
2004-05 finished scraping
2003-04 finished scraping
2002-03 finished scraping
2001-02 finished scraping
2000-01 finished scraping
1999-00 finished scraping
1998-99 finished scraping
1997-98 finished scraping
1996-97 finished scraping
1995-96 finished scraping
1994-95 finished scraping
1993-94 finished scraping
1992-93 finished scraping
1991-92 finished scraping
1990-91 finished scraping
1989-90 finished scraping
1988-89 finished scraping
1987-88 finished scraping
1986-87 finished scraping
1985-86 finished scraping
1984-85 finished scraping
1983-84 finished scraping
1982-83 finished scraping
1981-82 finished scraping
1980-81 finished scraping
1979-80 finished scraping
1978-79 finished scraping
1977-78 finished scraping
1976-77 finished scraping
1975-76 finished scraping
1974-75 finished scraping
1973-74 finished scraping
1972-73 finished scraping
1971-72 finished scraping
1970-71 finished scraping
1969-70 finished scraping
1968-69 finished scraping
1967-68 finished scraping
1966-67 finished scraping
1965-66 finished scraping
1964-65 finished scraping
1963-64 finished scraping
1962-63 finished scraping
1961-62 finished scraping
1960-61 finished scraping
1959-60 finished scraping

In [4]:
df = pd.DataFrame(list_rows)

In [5]:
df['Season']=season

In [6]:
df.set_axis(['0','Season'], axis=1, inplace=False)

                                                       0   Season
0                                                     []  2019-20
1                                                     []  2019-20
2      [Justin Abdelkader, 32, DET, LW, 49, 0, 3, 3, ...  2019-20
3      [Pontus Aberg, 26, TOR, LW, 5, 0, 1, 1, 0, 0, ...  2019-20
4      [Vitaly Abramov, 21, OTT, RW, 2, 1, 0, 1, 0, 2...  2019-20
...                                                  ...      ...
45618  [Norm Ullman*, 24, DET, C, 70, 24, 34, 58, -19...  1959-60
45619  [Moose Vasko, 24, CBH, D, 69, 3, 27, 30, 14, 1...  1959-60
45620  [Don Ward, 24, BOS, D, 31, 0, 1, 1, -1, 18, 0....  1959-60
45621  [Kenny Wharram, 26, CBH, RW, 59, 14, 11, 25, 1...  1959-60
45622  [Johnny Wilson, 30, TOR, LW, 70, 15, 16, 31, 2...  1959-60

[45623 rows x 2 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45623 entries, 0 to 45622
Data columns (total 2 columns):
0         45623 non-null object
Season    45623 non-null object
dtypes: object(2)
memory usage: 713.0+ KB

In [8]:
i = df.columns.get_loc(0)
df2 = df[0].str.split(",", expand=True)
df2=pd.concat([df.iloc[:, :i], df2, df.iloc[:, i+1:]], axis=1)

In [9]:
df2.head()

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,Season
0,[],None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,2019-20
1,[],None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,2019-20
2,[Justin Abdelkader,32,DET,LW,49,0,3,3,-14,25,...,40,0.0,565,11:32,26,103,38,31,55.1],2019-20
3,[Pontus Aberg,26,TOR,LW,5,0,1,1,0,0,...,4,0.0,44,8:42,1,1,0,0,],2019-20
4,[Vitaly Abramov,21,OTT,RW,2,1,0,1,0,2,...,3,33.3,12,5:47,0,0,0,0,],2019-20

In [10]:
df2[0] = df2[0].str.strip('[')
df2[26] = df2[26].str.strip(']')
df2 = df2.iloc[2:]
df2 = df2.reset_index(drop=True)

In [11]:
df2.head()

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,Season
0,Justin Abdelkader,32,DET,LW,49,0,3,3,-14,25,...,40,0.0,565,11:32,26,103,38,31,55.1,2019-20
1,Pontus Aberg,26,TOR,LW,5,0,1,1,0,0,...,4,0.0,44,8:42,1,1,0,0,,2019-20
2,Vitaly Abramov,21,OTT,RW,2,1,0,1,0,2,...,3,33.3,12,5:47,0,0,0,0,,2019-20
3,Noel Acciari,28,FLA,C,66,20,7,27,2,21,...,108,18.5,1054,15:58,103,121,381,414,47.9,2019-20
4,Andrew Agozzino,29,TOT,LW,22,1,2,3,3,4,...,10,10.0,162,7:21,7,25,38,37,50.7,2019-20

In [12]:
df2 = df2.set_axis(['Player', 'Age', 'Tm', 'Pos', 'GP', 'G', 'A', 'PTS', 'PlusMinus', 'PIM', 'PS', 'EV', 'PP', 'SH', 'GW', 'EV', 'PP', 'SH', 'S', 'Spct', 'TOI', 'ATOI', 'BLK', 'HIT', 'FOW', 'FOL', 'FOpct','Season'], axis=1, inplace=False)
df2.reset_index
df2.drop(df2[df2['Player'] == ']'].index, inplace = True)
df2.reset_index(drop=True)

,Player,Age,Tm,Pos,GP,G,A,PTS,PlusMinus,PIM,...,S,Spct,TOI,ATOI,BLK,HIT,FOW,FOL,FOpct,Season
0,Justin Abdelkader,32,DET,LW,49,0,3,3,-14,25,...,40,0.0,565,11:32,26,103,38,31,55.1,2019-20
1,Pontus Aberg,26,TOR,LW,5,0,1,1,0,0,...,4,0.0,44,8:42,1,1,0,0,,2019-20
2,Vitaly Abramov,21,OTT,RW,2,1,0,1,0,2,...,3,33.3,12,5:47,0,0,0,0,,2019-20
3,Noel Acciari,28,FLA,C,66,20,7,27,2,21,...,108,18.5,1054,15:58,103,121,381,414,47.9,2019-20
4,Andrew Agozzino,29,TOT,LW,22,1,2,3,3,4,...,10,10.0,162,7:21,7,25,38,37,50.7,2019-20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43689,Norm Ullman*,24,DET,C,70,24,34,58,-19,46,...,226,10.6,,],None,None,None,None,None,1959-60
43690,Moose Vasko,24,CBH,D,69,3,27,30,14,110,...,110,2.7,,],None,None,None,None,None,1959-60
43691,Don Ward,24,BOS,D,31,0,1,1,-1,18,...,11,0.0,,],None,None,None,None,None,1959-60
43692,Kenny Wharram,26,CBH,RW,59,14,11,25,11,16,...,119,11.8,,],None,None,None,None,None,1959-60
43693,Johnny Wilson,30,TOR,LW,70,15,16,31,2,6,...,98,15.3,,],None,None,None,None,None,1959-60

In [13]:
df2.dtypes

Player       object
Age          object
Tm           object
Pos          object
GP           object
G            object
A            object
PTS          object
PlusMinus    object
PIM          object
PS           object
EV           object
PP           object
SH           object
GW           object
EV           object
PP           object
SH           object
S            object
Spct         object
TOI          object
ATOI         object
BLK          object
HIT          object
FOW          object
FOL          object
FOpct        object
Season       object
dtype: object

In [13]:
df2.to_csv('../Capstone/Data/NHL_Skater_Data.csv', index=0)