# Initial Data Cleaning and EDA

In [1]:
# data handling
import sweetviz as sv
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as plt
import matplotlib.pyplot as plt
from pandas import DataFrame
%matplotlib inline

# splitting data
from sklearn import model_selection
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split

# evaluating models
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import roc_auc_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_recall_fscore_support
from scipy.stats import boxcox
from scipy import stats

# `logistic regression` model
from sklearn.linear_model import LogisticRegression

In [2]:
data = pd.read_csv('../../Capstone/Data/MLB_Pitching_Data.csv')

In [3]:
data.dtypes

name_common               object
age                      float64
mlb_ID                   float64
player_ID                 object
year_ID                    int64
team_ID                   object
stint_ID                   int64
lg_ID                     object
G                          int64
GS                         int64
IPouts                     int64
IPouts_start             float64
IPouts_relief            float64
RA                         int64
xRA                      float64
xRA_sprp_adj             float64
xRA_def_pitcher          float64
PPF                        int64
PPF_custom               float64
xRA_final                float64
BIP                        int64
BIP_perc                 float64
RS_def_total             float64
runs_above_avg           float64
runs_above_avg_adj       float64
runs_above_rep           float64
RpO_replacement          float64
GR_leverage_index_avg    float64
WAR                      float64
salary                   float64
teamRpG                  float64
oppRpG                   float64
pyth_exponent            float64
waa_win_perc             float64
WAA                      float64
WAA_adj                  float64
oppRpG_rep               float64
pyth_exponent_rep        float64
waa_win_perc_rep         float64
WAR_rep                  float64
ERA_plus                 float64
ER_lg                    float64
dtype: object

In [4]:
data.drop(data[data['year_ID'] < 1960].index, inplace = True)

In [5]:
data.reset_index(drop=True)

,name_common,age,mlb_ID,player_ID,year_ID,team_ID,stint_ID,lg_ID,G,GS,...,pyth_exponent,waa_win_perc,WAA,WAA_adj,oppRpG_rep,pyth_exponent_rep,waa_win_perc_rep,WAR_rep,ERA_plus,ER_lg
0,David Aardsma,22.0,430911.0,aardsda01,2004,SFG,1,NL,11,0,...,1.902,0.4803,-0.2167,-0.0298,4.75633,1.895,0.4914,0.0942,66.675000,5.334
1,David Aardsma,24.0,430911.0,aardsda01,2006,CHC,1,NL,45,0,...,1.909,0.5060,0.2700,-0.1301,4.97303,1.919,0.4896,0.4682,114.295833,27.431
2,David Aardsma,25.0,430911.0,aardsda01,2007,CHW,1,AL,25,0,...,1.924,0.4782,-0.5450,-0.1990,5.00394,1.920,0.4859,0.3459,74.086956,17.040
3,David Aardsma,26.0,430911.0,aardsda01,2008,BOS,1,AL,47,0,...,1.904,0.4836,-0.7708,-0.0632,4.81624,1.901,0.4888,0.5205,83.796667,25.139
4,David Aardsma,27.0,430911.0,aardsda01,2009,SEA,1,AL,73,0,...,1.899,0.5105,0.7665,0.1577,4.90529,1.911,0.4894,0.7666,168.910000,33.782
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31705,Joel Zumaya,24.0,451491.0,zumayjo01,2009,DET,1,AL,29,0,...,1.911,0.4900,-0.2900,-0.1339,4.91538,1.912,0.4884,0.3333,92.352941,15.700
31706,Joel Zumaya,25.0,451491.0,zumayjo01,2010,DET,1,AL,31,0,...,1.857,0.5132,0.4092,-0.0146,4.57553,1.872,0.4867,0.4089,163.509091,17.986
31707,Tony Zych,24.0,543964.0,zychto01,2015,SEA,1,AL,13,1,...,1.836,0.5197,0.2561,-0.0196,4.43938,1.855,0.4856,0.1866,158.700000,7.935
31708,Tony Zych,25.0,543964.0,zychto01,2016,SEA,1,AL,12,0,...,1.870,0.5011,0.0132,-0.0356,4.61444,1.877,0.4885,0.1397,126.080000,6.304
31709,Tony Zych,26.0,543964.0,zychto01,2017,SEA,1,AL,45,0,...,1.885,0.5148,0.6660,-0.0089,4.78879,1.899,0.4907,0.4123,157.950000,18.954

In [6]:
data.isna().any()

name_common              False
age                      False
mlb_ID                   False
player_ID                False
year_ID                  False
team_ID                  False
stint_ID                 False
lg_ID                    False
G                        False
GS                       False
IPouts                   False
IPouts_start              True
IPouts_relief             True
RA                       False
xRA                      False
xRA_sprp_adj              True
xRA_def_pitcher          False
PPF                      False
PPF_custom                True
xRA_final                 True
BIP                      False
BIP_perc                 False
RS_def_total             False
runs_above_avg            True
runs_above_avg_adj        True
runs_above_rep            True
RpO_replacement          False
GR_leverage_index_avg    False
WAR                       True
salary                    True
teamRpG                  False
oppRpG                    True
pyth_exponent             True
waa_win_perc              True
WAA                       True
WAA_adj                  False
oppRpG_rep                True
pyth_exponent_rep         True
waa_win_perc_rep          True
WAR_rep                   True
ERA_plus                  True
ER_lg                    False
dtype: bool

In [7]:
data = data.fillna(0)

In [8]:
data.isna().any()

name_common              False
age                      False
mlb_ID                   False
player_ID                False
year_ID                  False
team_ID                  False
stint_ID                 False
lg_ID                    False
G                        False
GS                       False
IPouts                   False
IPouts_start             False
IPouts_relief            False
RA                       False
xRA                      False
xRA_sprp_adj             False
xRA_def_pitcher          False
PPF                      False
PPF_custom               False
xRA_final                False
BIP                      False
BIP_perc                 False
RS_def_total             False
runs_above_avg           False
runs_above_avg_adj       False
runs_above_rep           False
RpO_replacement          False
GR_leverage_index_avg    False
WAR                      False
salary                   False
teamRpG                  False
oppRpG                   False
pyth_exponent            False
waa_win_perc             False
WAA                      False
WAA_adj                  False
oppRpG_rep               False
pyth_exponent_rep        False
waa_win_perc_rep         False
WAR_rep                  False
ERA_plus                 False
ER_lg                    False
dtype: bool

In [9]:
data.to_csv('../../Capstone/Data/FirstClean_MLB_Pitching_Data.csv', index=0)

In [10]:
my_report = sv.analyze(data, target_feat='WAR')
my_report.show_html('../../Capstone/EDA HTML files/PitchingEDA.html')

:FEATURES DONE:                    |█████████████████████| [100%]   00:27  -> (00:00 left)
:PAIRWISE DONE:                    |█████████████████████| [100%]   00:02  -> (00:00 left)

Creating Associations graph... DONE!