# Initial Data Cleaning and EDA

In [1]:
# data handling
import sweetviz as sv
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as plt
import matplotlib.pyplot as plt
from pandas import DataFrame
%matplotlib inline

# splitting data
from sklearn import model_selection
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split

# evaluating models
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import roc_auc_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_recall_fscore_support
from scipy.stats import boxcox
from scipy import stats

# `logistic regression` model
from sklearn.linear_model import LogisticRegression

In [2]:
data = pd.read_csv('../Capstone/Data/MLB_Batting_Data.csv')

In [3]:
data.dtypes

name_common            object
age                   float64
mlb_ID                float64
player_ID              object
year_ID                 int64
team_ID                object
stint_ID                int64
lg_ID                  object
PA                      int64
G                       int64
Inn                   float64
runs_bat              float64
runs_br               float64
runs_dp               float64
runs_field            float64
runs_infield          float64
runs_outfield         float64
runs_catcher          float64
runs_good_plays       float64
runs_defense          float64
runs_position         float64
runs_position_p       float64
runs_replacement      float64
runs_above_rep        float64
runs_above_avg        float64
runs_above_avg_off    float64
runs_above_avg_def    float64
WAA                   float64
WAA_off               float64
WAA_def               float64
WAR                   float64
WAR_def               float64
WAR_off               float64
WAR_rep               float64
salary                float64
pitcher                object
teamRpG               float64
oppRpG                float64
oppRpPA_rep           float64
oppRpG_rep            float64
pyth_exponent         float64
pyth_exponent_rep     float64
waa_win_perc          float64
waa_win_perc_off      float64
waa_win_perc_def      float64
waa_win_perc_rep      float64
OPS_plus              float64
TOB_lg                float64
TB_lg                 float64
dtype: object

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 107357 entries, 0 to 107356
Data columns (total 49 columns):
name_common           107357 non-null object
age                   107206 non-null float64
mlb_ID                107309 non-null float64
player_ID             107357 non-null object
year_ID               107357 non-null int64
team_ID               107357 non-null object
stint_ID              107357 non-null int64
lg_ID                 106620 non-null object
PA                    107357 non-null int64
G                     107357 non-null int64
Inn                   71100 non-null float64
runs_bat              107357 non-null float64
runs_br               107357 non-null float64
runs_dp               107357 non-null float64
runs_field            107357 non-null float64
runs_infield          71100 non-null float64
runs_outfield         71100 non-null float64
runs_catcher          71100 non-null float64
runs_good_plays       24108 non-null float64
runs_defense          107357 non-null float64
runs_position         107357 non-null float64
runs_position_p       107357 non-null float64
runs_replacement      107357 non-null float64
runs_above_rep        107357 non-null float64
runs_above_avg        107357 non-null float64
runs_above_avg_off    107357 non-null float64
runs_above_avg_def    107357 non-null float64
WAA                   99558 non-null float64
WAA_off               99558 non-null float64
WAA_def               99558 non-null float64
WAR                   99558 non-null float64
WAR_def               99558 non-null float64
WAR_off               99558 non-null float64
WAR_rep               99558 non-null float64
salary                40626 non-null float64
pitcher               107357 non-null object
teamRpG               99558 non-null float64
oppRpG                107357 non-null float64
oppRpPA_rep           107357 non-null float64
oppRpG_rep            99558 non-null float64
pyth_exponent         99558 non-null float64
pyth_exponent_rep     99558 non-null float64
waa_win_perc          99558 non-null float64
waa_win_perc_off      99558 non-null float64
waa_win_perc_def      99558 non-null float64
waa_win_perc_rep      99558 non-null float64
OPS_plus              90521 non-null float64
TOB_lg                107357 non-null float64
TB_lg                 107357 non-null float64
dtypes: float64(40), int64(4), object(5)
memory usage: 40.1+ MB

In [5]:
a=data.pitcher.unique()
print(sorted(a))

['N', 'Y']

In [6]:
data.drop(data[data['pitcher'] == 'Y'].index, inplace = True)

In [7]:
data.drop(data[data['year_ID'] < 1960].index, inplace = True)

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 35504 entries, 15 to 107339
Data columns (total 49 columns):
name_common           35504 non-null object
age                   35504 non-null float64
mlb_ID                35504 non-null float64
player_ID             35504 non-null object
year_ID               35504 non-null int64
team_ID               35504 non-null object
stint_ID              35504 non-null int64
lg_ID                 35504 non-null object
PA                    35504 non-null int64
G                     35504 non-null int64
Inn                   35504 non-null float64
runs_bat              35504 non-null float64
runs_br               35504 non-null float64
runs_dp               35504 non-null float64
runs_field            35504 non-null float64
runs_infield          35504 non-null float64
runs_outfield         35504 non-null float64
runs_catcher          35504 non-null float64
runs_good_plays       11636 non-null float64
runs_defense          35504 non-null float64
runs_position         35504 non-null float64
runs_position_p       35504 non-null float64
runs_replacement      35504 non-null float64
runs_above_rep        35504 non-null float64
runs_above_avg        35504 non-null float64
runs_above_avg_off    35504 non-null float64
runs_above_avg_def    35504 non-null float64
WAA                   35504 non-null float64
WAA_off               35504 non-null float64
WAA_def               35504 non-null float64
WAR                   35504 non-null float64
WAR_def               35504 non-null float64
WAR_off               35504 non-null float64
WAR_rep               35504 non-null float64
salary                17896 non-null float64
pitcher               35504 non-null object
teamRpG               35504 non-null float64
oppRpG                35504 non-null float64
oppRpPA_rep           35504 non-null float64
oppRpG_rep            35504 non-null float64
pyth_exponent         35504 non-null float64
pyth_exponent_rep     35504 non-null float64
waa_win_perc          35504 non-null float64
waa_win_perc_off      35504 non-null float64
waa_win_perc_def      35504 non-null float64
waa_win_perc_rep      35504 non-null float64
OPS_plus              35341 non-null float64
TOB_lg                35504 non-null float64
TB_lg                 35504 non-null float64
dtypes: float64(40), int64(4), object(5)
memory usage: 13.5+ MB

In [9]:
data.drop(['pitcher'], axis=1)

,name_common,age,mlb_ID,player_ID,year_ID,team_ID,stint_ID,lg_ID,PA,G,...,oppRpG_rep,pyth_exponent,pyth_exponent_rep,waa_win_perc,waa_win_perc_off,waa_win_perc_def,waa_win_perc_rep,OPS_plus,TOB_lg,TB_lg
15,Hank Aaron,26.0,110001.0,aaronha01,1960,MLN,1,NL,664,153,...,4.07285,1.854,1.828,0.5366,0.5266,0.5052,0.4824,156.1662,211.285,229.687
16,Hank Aaron,27.0,110001.0,aaronha01,1961,MLN,1,NL,671,155,...,4.38978,1.894,1.867,0.5452,0.5295,0.5132,0.4829,163.3027,218.152,244.516
17,Hank Aaron,28.0,110001.0,aaronha01,1962,MLN,1,NL,667,156,...,4.34324,1.891,1.861,0.5382,0.5343,0.5015,0.4831,169.8299,222.244,239.464
18,Hank Aaron,29.0,110001.0,aaronha01,1963,MLN,1,NL,714,161,...,3.65096,1.809,1.773,0.5396,0.5429,0.4914,0.4813,179.1695,224.696,238.707
19,Hank Aaron,30.0,110001.0,aaronha01,1964,MLN,1,NL,634,145,...,3.86564,1.827,1.802,0.5299,0.5270,0.4983,0.4820,152.6831,204.402,223.896
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107335,Paul Zuvella,27.0,124789.0,zuvelpa01,1986,NYY,1,AL,57,21,...,4.54481,1.862,1.881,0.4537,0.4566,0.5023,0.4905,-22.6108,17.395,19.493
107336,Paul Zuvella,28.0,124789.0,zuvelpa01,1987,NYY,1,AL,36,14,...,4.84613,1.899,1.915,0.4569,0.4631,0.4980,0.4914,-5.2110,11.291,14.406
107337,Paul Zuvella,29.0,124789.0,zuvelpa01,1988,CLE,1,AL,146,51,...,4.28123,1.850,1.850,0.4771,0.4890,0.4937,0.4896,56.4277,45.126,51.233
107338,Paul Zuvella,30.0,124789.0,zuvelpa01,1989,CLE,1,AL,60,24,...,4.23326,1.850,1.844,0.4976,0.5012,0.4994,0.4903,99.1113,19.620,22.353
107339,Paul Zuvella,32.0,124789.0,zuvelpa01,1991,KCR,1,AL,0,2,...,4.47535,1.868,1.868,0.4695,0.5000,0.4695,0.5000,NaN,0.000,0.000

In [10]:
data.reset_index(drop=True)

,name_common,age,mlb_ID,player_ID,year_ID,team_ID,stint_ID,lg_ID,PA,G,...,oppRpG_rep,pyth_exponent,pyth_exponent_rep,waa_win_perc,waa_win_perc_off,waa_win_perc_def,waa_win_perc_rep,OPS_plus,TOB_lg,TB_lg
0,Hank Aaron,26.0,110001.0,aaronha01,1960,MLN,1,NL,664,153,...,4.07285,1.854,1.828,0.5366,0.5266,0.5052,0.4824,156.1662,211.285,229.687
1,Hank Aaron,27.0,110001.0,aaronha01,1961,MLN,1,NL,671,155,...,4.38978,1.894,1.867,0.5452,0.5295,0.5132,0.4829,163.3027,218.152,244.516
2,Hank Aaron,28.0,110001.0,aaronha01,1962,MLN,1,NL,667,156,...,4.34324,1.891,1.861,0.5382,0.5343,0.5015,0.4831,169.8299,222.244,239.464
3,Hank Aaron,29.0,110001.0,aaronha01,1963,MLN,1,NL,714,161,...,3.65096,1.809,1.773,0.5396,0.5429,0.4914,0.4813,179.1695,224.696,238.707
4,Hank Aaron,30.0,110001.0,aaronha01,1964,MLN,1,NL,634,145,...,3.86564,1.827,1.802,0.5299,0.5270,0.4983,0.4820,152.6831,204.402,223.896
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35499,Paul Zuvella,27.0,124789.0,zuvelpa01,1986,NYY,1,AL,57,21,...,4.54481,1.862,1.881,0.4537,0.4566,0.5023,0.4905,-22.6108,17.395,19.493
35500,Paul Zuvella,28.0,124789.0,zuvelpa01,1987,NYY,1,AL,36,14,...,4.84613,1.899,1.915,0.4569,0.4631,0.4980,0.4914,-5.2110,11.291,14.406
35501,Paul Zuvella,29.0,124789.0,zuvelpa01,1988,CLE,1,AL,146,51,...,4.28123,1.850,1.850,0.4771,0.4890,0.4937,0.4896,56.4277,45.126,51.233
35502,Paul Zuvella,30.0,124789.0,zuvelpa01,1989,CLE,1,AL,60,24,...,4.23326,1.850,1.844,0.4976,0.5012,0.4994,0.4903,99.1113,19.620,22.353
35503,Paul Zuvella,32.0,124789.0,zuvelpa01,1991,KCR,1,AL,0,2,...,4.47535,1.868,1.868,0.4695,0.5000,0.4695,0.5000,NaN,0.000,0.000

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 35504 entries, 15 to 107339
Data columns (total 49 columns):
name_common           35504 non-null object
age                   35504 non-null float64
mlb_ID                35504 non-null float64
player_ID             35504 non-null object
year_ID               35504 non-null int64
team_ID               35504 non-null object
stint_ID              35504 non-null int64
lg_ID                 35504 non-null object
PA                    35504 non-null int64
G                     35504 non-null int64
Inn                   35504 non-null float64
runs_bat              35504 non-null float64
runs_br               35504 non-null float64
runs_dp               35504 non-null float64
runs_field            35504 non-null float64
runs_infield          35504 non-null float64
runs_outfield         35504 non-null float64
runs_catcher          35504 non-null float64
runs_good_plays       11636 non-null float64
runs_defense          35504 non-null float64
runs_position         35504 non-null float64
runs_position_p       35504 non-null float64
runs_replacement      35504 non-null float64
runs_above_rep        35504 non-null float64
runs_above_avg        35504 non-null float64
runs_above_avg_off    35504 non-null float64
runs_above_avg_def    35504 non-null float64
WAA                   35504 non-null float64
WAA_off               35504 non-null float64
WAA_def               35504 non-null float64
WAR                   35504 non-null float64
WAR_def               35504 non-null float64
WAR_off               35504 non-null float64
WAR_rep               35504 non-null float64
salary                17896 non-null float64
pitcher               35504 non-null object
teamRpG               35504 non-null float64
oppRpG                35504 non-null float64
oppRpPA_rep           35504 non-null float64
oppRpG_rep            35504 non-null float64
pyth_exponent         35504 non-null float64
pyth_exponent_rep     35504 non-null float64
waa_win_perc          35504 non-null float64
waa_win_perc_off      35504 non-null float64
waa_win_perc_def      35504 non-null float64
waa_win_perc_rep      35504 non-null float64
OPS_plus              35341 non-null float64
TOB_lg                35504 non-null float64
TB_lg                 35504 non-null float64
dtypes: float64(40), int64(4), object(5)
memory usage: 13.5+ MB

In [12]:
data.to_csv('../Capstone/Data/FirstClean_MLB_Batting_Data.csv', index=0)

In [13]:
my_report = sv.analyze(data, target_feat='WAR')
my_report.show_html('../Capstone/EDA_files/BattingEDA.html')

:FEATURES DONE:                    |█████████████████████| [100%]   00:31  -> (00:00 left)
:PAIRWISE DONE:                    |█████████████████████| [100%]   00:04  -> (00:00 left)

Creating Associations graph... DONE!